using FluentAssertions;
using Life.Domain.Aggregates;
using Life.Domain.ValueObjects;
using Life.Domain.Services;
using Life.Domain.Events;
using Life.Domain.Exceptions;

namespace Life.Domain.Tests.Aggregates
{
    public class GameSessionTests
    {
        [Fact]
        public void GameSession_Should_Initialize_With_Correct_Values()
        {
            // Arrange
            var initialBoard = new Board(10, 10, new[] { (1, 1), (2, 1), (3, 1) });
            var name = "Test Session";
            var createdBy = "TestUser";
            var settings = SessionSettings.Default;

            // Act
            var session = new GameSession(name, initialBoard, createdBy, settings);

            // Assert
            session.Name.Should().Be(name);
            session.CreatedBy.Should().Be(createdBy);
            session.CurrentGeneration.Should().Be(0);
            session.Status.Should().Be(SessionStatus.Active);
            session.Dimensions.Should().Be(initialBoard.Dimensions);
            session.GetCurrentBoard().Should().BeEquivalentTo(initialBoard);
            session.CanModify.Should().BeTrue();
        }

        [Fact]
        public void GameSession_Should_Create_Initial_Snapshot_On_Creation()
        {
            // Arrange
            var initialBoard = new Board(5, 5, new[] { (2, 2) });
            var session = new GameSession("Test", initialBoard, "TestUser");

            // Act
            var snapshots = session.GetSnapshots();

            // Assert
            snapshots.Should().HaveCount(1);
            snapshots.First().Generation.Should().Be(0);
            snapshots.First().Description.Should().Be("Initial board state");
            snapshots.First().IsAutoGenerated.Should().BeFalse();
        }

        [Fact]
        public void AdvanceGeneration_Should_Progress_To_Next_Generation()
        {
            // Arrange - Create a simple blinker pattern
            var initialBoard = new Board(5, 5, new[] { (2, 1), (2, 2), (2, 3) });
            var session = new GameSession("Blinker Test", initialBoard, "TestUser");

            // Act
            var nextBoard = session.AdvanceGeneration();

            // Assert
            session.CurrentGeneration.Should().Be(1);
            nextBoard.Should().NotBeNull();
            
            // Blinker should rotate 90 degrees
            var aliveCells = nextBoard.Alive().ToList();
            aliveCells.Should().Contain((1, 2));
            aliveCells.Should().Contain((2, 2));
            aliveCells.Should().Contain((3, 2));
        }

        [Fact]
        public void AdvanceGenerations_Should_Progress_Multiple_Generations()
        {
            // Arrange
            var initialBoard = new Board(5, 5, new[] { (2, 1), (2, 2), (2, 3) });
            var session = new GameSession("Multi-Generation Test", initialBoard, "TestUser");

            // Act
            var finalBoard = session.AdvanceGenerations(2);

            // Assert
            session.CurrentGeneration.Should().Be(2);
            
            // After 2 generations, blinker should be back to original orientation
            var aliveCells = finalBoard.Alive().ToList();
            aliveCells.Should().Contain((2, 1));
            aliveCells.Should().Contain((2, 2));
            aliveCells.Should().Contain((2, 3));
        }

        [Fact]
        public void CreateSnapshot_Should_Create_Manual_Snapshot()
        {
            // Arrange
            var initialBoard = new Board(5, 5, new[] { (2, 2) });
            var session = new GameSession("Snapshot Test", initialBoard, "TestUser");
            var description = "Manual test snapshot";

            // Act
            var snapshot = session.CreateSnapshot(description);

            // Assert
            snapshot.Should().NotBeNull();
            snapshot.Description.Should().Be(description);
            snapshot.Generation.Should().Be(0);
            snapshot.IsAutoGenerated.Should().BeFalse();
            
            session.GetSnapshots().Should().HaveCount(2); // Initial + manual
        }

        [Fact]
        public void RestoreFromSnapshot_Should_Restore_Previous_State()
        {
            // Arrange
            var initialBoard = new Board(5, 5, new[] { (2, 1), (2, 2), (2, 3) });
            var session = new GameSession("Restore Test", initialBoard, "TestUser");
            
            // Take snapshot at generation 0
            var initialSnapshot = session.GetSnapshots().First();
            
            // Advance to generation 1
            session.AdvanceGeneration();
            session.CurrentGeneration.Should().Be(1);

            // Act - Restore to generation 0
            var restoredBoard = session.RestoreFromSnapshot(initialSnapshot.Id);

            // Assert
            session.CurrentGeneration.Should().Be(0);
            var aliveCells = restoredBoard.Alive().ToList();
            aliveCells.Should().Contain((2, 1));
            aliveCells.Should().Contain((2, 2));
            aliveCells.Should().Contain((2, 3));
        }

        [Fact]
        public void RestoreFromSnapshot_Should_Throw_When_Snapshot_Not_Found()
        {
            // Arrange
            var initialBoard = new Board(5, 5, new[] { (2, 2) });
            var session = new GameSession("Error Test", initialBoard, "TestUser");
            var nonExistentSnapshotId = Guid.NewGuid();

            // Act & Assert
            session.Invoking(s => s.RestoreFromSnapshot(nonExistentSnapshotId))
                .Should().Throw<SnapshotNotFoundException>()
                .WithMessage($"Snapshot {nonExistentSnapshotId} not found in session {session.Id}");
        }

        [Fact]
        public void RunToCompletion_Should_Detect_Stable_State()
        {
            // Arrange - Create a block pattern (stable)
            var stableBoard = new Board(4, 4, new[] { (1, 1), (1, 2), (2, 1), (2, 2) });
            var session = new GameSession("Stable Test", stableBoard, "TestUser");

            // Act
            var result = session.RunToCompletion(maxIterations: 10);

            // Assert
            result.Stable.Should().BeTrue();
            result.Cyclic.Should().BeFalse();
            session.Status.Should().Be(SessionStatus.Completed);
        }

        [Fact]
        public void RunToCompletion_Should_Detect_Cyclic_State()
        {
            // Arrange - Create a blinker pattern (period-2 oscillator)
            var cyclicBoard = new Board(5, 5, new[] { (2, 1), (2, 2), (2, 3) });
            var session = new GameSession("Cyclic Test", cyclicBoard, "TestUser");

            // Act
            var result = session.RunToCompletion(maxIterations: 10);

            // Assert
            result.Cyclic.Should().BeTrue();
            result.Stable.Should().BeFalse();
            result.CycleLength.Should().Be(2);
            session.Status.Should().Be(SessionStatus.Completed);
        }

        [Fact]
        public void Pause_And_Resume_Should_Change_Session_Status()
        {
            // Arrange
            var initialBoard = new Board(5, 5, new[] { (2, 2) });
            var session = new GameSession("Status Test", initialBoard, "TestUser");

            // Act - Pause
            session.Pause();

            // Assert
            session.Status.Should().Be(SessionStatus.Paused);
            session.CanModify.Should().BeFalse();

            // Act - Resume
            session.Resume();

            // Assert
            session.Status.Should().Be(SessionStatus.Active);
            session.CanModify.Should().BeTrue();
        }

        [Fact]
        public void Archive_Should_Set_Status_To_Archived()
        {
            // Arrange
            var initialBoard = new Board(5, 5, new[] { (2, 2) });
            var session = new GameSession("Archive Test", initialBoard, "TestUser");
            var reason = "Test archive";

            // Act
            session.Archive(reason);

            // Assert
            session.Status.Should().Be(SessionStatus.Archived);
            session.CanModify.Should().BeFalse();
        }

        [Fact]
        public void GetStatistics_Should_Return_Correct_Metrics()
        {
            // Arrange - Use a stable block that won't become extinct
            var initialBoard = new Board(10, 10, new[] { (4, 4), (4, 5), (5, 4), (5, 5) }); // Block pattern
            var session = new GameSession("Stats Test", initialBoard, "TestUser");
            
            // Create a test snapshot first, then advance generations
            session.CreateSnapshot("Test snapshot");
            session.AdvanceGenerations(3); // Use fewer generations to avoid potential issues

            // Act
            var stats = session.GetStatistics();

            // Assert
            stats.SessionId.Should().Be(session.Id);
            stats.Name.Should().Be("Stats Test");
            stats.TotalGenerations.Should().Be(3);
            stats.SnapshotCount.Should().Be(3); // Initial + manual + bulk advancement
            stats.Status.Should().Be(SessionStatus.Active);
        }

        [Fact]
        public void CreateFromPattern_Should_Create_Session_With_Known_Pattern()
        {
            // Arrange
            var dimensions = new BoardDimensions(20, 20);
            var center = new Position(10, 10);

            // Act
            var session = GameSessionService.CreateFromPattern(
                "Glider Test",
                "TestUser",
                dimensions,
                PatternType.Glider,
                center
            );

            // Assert
            session.Name.Should().Be("Glider Test");
            session.CreatedBy.Should().Be("TestUser");
            session.Dimensions.Should().Be(dimensions);
            
            var currentBoard = session.GetCurrentBoard();
            var aliveCells = currentBoard.Alive().ToList();
            aliveCells.Should().HaveCount(5); // Glider has 5 alive cells
        }

        [Fact]
        public void AutoSnapshot_Should_Create_Snapshots_At_Intervals()
        {
            // Arrange
            var settings = new SessionSettings(
                autoSnapshotEnabled: true,
                autoSnapshotInterval: 3,
                maxSnapshots: 10
            );
            var initialBoard = new Board(10, 10, new[] { (5, 4), (5, 5), (5, 6) });
            var session = new GameSession("Auto Snapshot Test", initialBoard, "TestUser", settings);

            // Act - Advance generation by generation to trigger auto-snapshots
            session.AdvanceGeneration(); // Gen 1
            session.AdvanceGeneration(); // Gen 2  
            session.AdvanceGeneration(); // Gen 3 - should trigger auto-snapshot

            // Assert
            var snapshots = session.GetSnapshots();
            snapshots.Should().HaveCount(2); // Initial + auto-snapshot
            snapshots.Should().Contain(s => s.IsAutoGenerated && s.Generation == 3);
        }

        [Fact]
        public void Session_Should_Raise_Domain_Events()
        {
            // Arrange
            var initialBoard = new Board(5, 5, new[] { (2, 2) });
            
            // Act
            var session = new GameSession("Event Test", initialBoard, "TestUser");

            // Assert
            var events = session.DomainEvents;
            events.Should().NotBeEmpty();
            events.Should().Contain(e => e is GameSessionCreated);
            events.Should().Contain(e => e is SessionSnapshotCreated);
        }
    }
}