using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Life.Infrastructure.Entities
{
    /// <summary>
    /// Entity for persisting GameSession snapshots
    /// Separate from SnapshotEntity to maintain clean separation between Board and GameSession concerns
    /// </summary>
    public sealed class SessionSnapshotEntity
    {
        [Key]
        public Guid Id { get; set; }

        [Required]
        public Guid SessionId { get; set; }

        [Required]
        public int Generation { get; set; }

        [Required]
        public byte[] BoardData { get; set; } = Array.Empty<byte>();

        [MaxLength(500)]
        public string? Description { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        public bool IsAutoGenerated { get; set; } = false;

        // Navigation property
        [ForeignKey(nameof(SessionId))]
        public GameSessionEntity Session { get; set; } = null!;
    }
}