namespace Life.Domain.ValueObjects
{
    /// <summary>
    /// Represents session configuration settings
    /// </summary>
    public record SessionSettings
    {
        public bool AutoSnapshotEnabled { get; init; }
        public int AutoSnapshotInterval { get; init; }
        public int MaxSnapshots { get; init; }
        public TimeSpan SessionTimeout { get; init; }
        public bool AllowConcurrentAccess { get; init; }

        public SessionSettings(
            bool autoSnapshotEnabled = true,
            int autoSnapshotInterval = 10,
            int maxSnapshots = 50,
            TimeSpan? sessionTimeout = null,
            bool allowConcurrentAccess = false)
        {
            if (autoSnapshotInterval <= 0)
                throw new ArgumentOutOfRangeException(nameof(autoSnapshotInterval), "Auto snapshot interval must be positive");
                
            if (maxSnapshots < 0)
                throw new ArgumentOutOfRangeException(nameof(maxSnapshots), "Max snapshots cannot be negative");

            AutoSnapshotEnabled = autoSnapshotEnabled;
            AutoSnapshotInterval = autoSnapshotInterval;
            MaxSnapshots = maxSnapshots;
            SessionTimeout = sessionTimeout ?? TimeSpan.FromHours(24);
            AllowConcurrentAccess = allowConcurrentAccess;
        }

        public static SessionSettings Default => new();

        public static SessionSettings Performance => new(
            autoSnapshotEnabled: false,
            maxSnapshots: 10,
            sessionTimeout: TimeSpan.FromMinutes(30),
            allowConcurrentAccess: true
        );

        public static SessionSettings Educational => new(
            autoSnapshotEnabled: true,
            autoSnapshotInterval: 5,
            maxSnapshots: 100,
            sessionTimeout: TimeSpan.FromHours(8),
            allowConcurrentAccess: false
        );
    }

    /// <summary>
    /// Represents a snapshot of game session state
    /// </summary>
    public sealed record SessionSnapshot
    {
        public Guid Id { get; init; }
        public Guid SessionId { get; init; }
        public int Generation { get; init; }
        public byte[] BoardData { get; init; }
        public string Description { get; init; }
        public DateTime CreatedAt { get; init; }
        public bool IsAutoGenerated { get; init; }

        public SessionSnapshot(
            Guid id,
            Guid sessionId,
            int generation,
            byte[] boardData,
            string description,
            DateTime createdAt,
            bool isAutoGenerated)
        {
            if (generation < 0)
                throw new ArgumentOutOfRangeException(nameof(generation), "Generation cannot be negative");
                
            if (boardData == null || boardData.Length == 0)
                throw new ArgumentException("Board data cannot be null or empty", nameof(boardData));
                
            if (string.IsNullOrWhiteSpace(description))
                throw new ArgumentException("Description cannot be empty", nameof(description));

            Id = id;
            SessionId = sessionId;
            Generation = generation;
            BoardData = boardData;
            Description = description;
            CreatedAt = createdAt;
            IsAutoGenerated = isAutoGenerated;
        }
    }

    /// <summary>
    /// Represents session statistics and metrics
    /// </summary>
    public sealed record SessionStatistics(
        Guid SessionId,
        string Name,
        int TotalGenerations,
        int SnapshotCount,
        TimeSpan SessionDuration,
        int CurrentPopulation,
        SessionStatus Status,
        DateTime LastActivity);

    /// <summary>
    /// Session status enumeration
    /// </summary>
    public enum SessionStatus
    {
        Active,
        Paused,
        Completed,
        Archived
    }
}