using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Life.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddGameSessionEntities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "GameSessions",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Width = table.Column<int>(type: "int", nullable: false),
                    Height = table.Column<int>(type: "int", nullable: false),
                    CurrentGeneration = table.Column<int>(type: "int", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    LastModified = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    AutoSnapshotEnabled = table.Column<bool>(type: "bit", nullable: false),
                    AutoSnapshotInterval = table.Column<int>(type: "int", nullable: false),
                    MaxSnapshots = table.Column<int>(type: "int", nullable: false),
                    SessionTimeoutMs = table.Column<long>(type: "bigint", nullable: false),
                    AllowConcurrentAccess = table.Column<bool>(type: "bit", nullable: false),
                    CurrentBoardId = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GameSessions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_GameSessions_Boards_CurrentBoardId",
                        column: x => x.CurrentBoardId,
                        principalTable: "Boards",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "SessionSnapshots",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SessionId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Generation = table.Column<int>(type: "int", nullable: false),
                    BoardData = table.Column<byte[]>(type: "varbinary(max)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    IsAutoGenerated = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SessionSnapshots", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SessionSnapshots_GameSessions_SessionId",
                        column: x => x.SessionId,
                        principalTable: "GameSessions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_GameSessions_CreatedAt",
                table: "GameSessions",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_GameSessions_CreatedBy",
                table: "GameSessions",
                column: "CreatedBy");

            migrationBuilder.CreateIndex(
                name: "IX_GameSessions_CreatedBy_Status",
                table: "GameSessions",
                columns: new[] { "CreatedBy", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_GameSessions_CurrentBoardId",
                table: "GameSessions",
                column: "CurrentBoardId");

            migrationBuilder.CreateIndex(
                name: "IX_GameSessions_Status",
                table: "GameSessions",
                column: "Status");

            migrationBuilder.CreateIndex(
                name: "IX_SessionSnapshots_CreatedAt",
                table: "SessionSnapshots",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_SessionSnapshots_SessionId",
                table: "SessionSnapshots",
                column: "SessionId");

            migrationBuilder.CreateIndex(
                name: "IX_SessionSnapshots_SessionId_Generation",
                table: "SessionSnapshots",
                columns: new[] { "SessionId", "Generation" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_SessionSnapshots_SessionId_IsAutoGenerated",
                table: "SessionSnapshots",
                columns: new[] { "SessionId", "IsAutoGenerated" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SessionSnapshots");

            migrationBuilder.DropTable(
                name: "GameSessions");
        }
    }
}
