// <auto-generated />
using System;
using Life.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Life.Infrastructure.Migrations
{
    [DbContext(typeof(LifeDbContext))]
    [Migration("20250929041022_AddGameSessionEntities")]
    partial class AddGameSessionEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Life.Infrastructure.Entities.BoardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Life.Infrastructure.Entities.GameSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowConcurrentAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoSnapshotEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("AutoSnapshotInterval")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrentBoardId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CurrentGeneration")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxSnapshots")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SessionTimeoutMs")
                        .HasColumnType("bigint")
                        .HasColumnName("SessionTimeoutMs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CurrentBoardId");

                    b.HasIndex("Status");

                    b.HasIndex("CreatedBy", "Status");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Life.Infrastructure.Entities.SessionSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("BoardData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "Generation")
                        .IsUnique();

                    b.HasIndex("SessionId", "IsAutoGenerated");

                    b.ToTable("SessionSnapshots");
                });

            modelBuilder.Entity("Life.Infrastructure.Entities.SnapshotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Generation")
                        .IsUnique();

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Life.Infrastructure.Entities.GameSessionEntity", b =>
                {
                    b.HasOne("Life.Infrastructure.Entities.BoardEntity", "CurrentBoard")
                        .WithMany()
                        .HasForeignKey("CurrentBoardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentBoard");
                });

            modelBuilder.Entity("Life.Infrastructure.Entities.SessionSnapshotEntity", b =>
                {
                    b.HasOne("Life.Infrastructure.Entities.GameSessionEntity", "Session")
                        .WithMany("Snapshots")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Life.Infrastructure.Entities.GameSessionEntity", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
