using Life.Infrastructure.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace Life.Infrastructure.Data
{
    public sealed class LifeDbContext : DbContext
    {
        public DbSet<BoardEntity> Boards => Set<BoardEntity>();
        public DbSet<SnapshotEntity> Snapshots => Set<SnapshotEntity>();
        public DbSet<GameSessionEntity> GameSessions => Set<GameSessionEntity>();
        public DbSet<SessionSnapshotEntity> SessionSnapshots => Set<SessionSnapshotEntity>();

        public LifeDbContext(DbContextOptions<LifeDbContext> o) : base(o) { }

        protected override void OnModelCreating(ModelBuilder b)
        {
            // Existing Board entities
            b.Entity<BoardEntity>().HasKey(x => x.Id);
            b.Entity<SnapshotEntity>().HasKey(x => x.Id);
            b.Entity<SnapshotEntity>().HasIndex(x => new { x.BoardId, x.Generation }).IsUnique();

            // GameSession entities
            b.Entity<GameSessionEntity>(entity =>
            {
                entity.HasKey(x => x.Id);
                
                // Indexes for common queries
                entity.HasIndex(x => x.CreatedBy);
                entity.HasIndex(x => x.Status);
                entity.HasIndex(x => x.CreatedAt);
                entity.HasIndex(x => new { x.CreatedBy, x.Status });
                
                // Current board relationship (optional)
                entity.HasOne(x => x.CurrentBoard)
                      .WithMany()
                      .HasForeignKey(x => x.CurrentBoardId)
                      .OnDelete(DeleteBehavior.SetNull);
                
                // Configure SessionTimeout storage
                entity.Property(x => x.SessionTimeoutMs)
                      .HasColumnName("SessionTimeoutMs");
                
                // Ignore the computed property
                entity.Ignore(x => x.SessionTimeout);
            });

            b.Entity<SessionSnapshotEntity>(entity =>
            {
                entity.HasKey(x => x.Id);
                
                // Indexes for efficient queries
                entity.HasIndex(x => x.SessionId);
                entity.HasIndex(x => new { x.SessionId, x.Generation }).IsUnique();
                entity.HasIndex(x => x.CreatedAt);
                entity.HasIndex(x => new { x.SessionId, x.IsAutoGenerated });
                
                // Relationship with GameSession
                entity.HasOne(x => x.Session)
                      .WithMany(x => x.Snapshots)
                      .HasForeignKey(x => x.SessionId)
                      .OnDelete(DeleteBehavior.Cascade);
            });
        }
    }
}
