# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copy all project files first for dependency resolution
COPY ["src/Life.Api/Life.Api.csproj", "Life.Api/"]
COPY ["src/Life.Application/Life.Application.csproj", "Life.Application/"]
COPY ["src/Life.Domain/Life.Domain.csproj", "Life.Domain/"]
COPY ["src/Life.Infrastructure/Life.Infrastructure.csproj", "Life.Infrastructure/"]

# Restore dependencies
RUN dotnet restore "./Life.Api/Life.Api.csproj"

# Copy all source code
COPY ["src/", "."]

WORKDIR "/src/Life.Api"
RUN dotnet build "./Life.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Life.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Life.Api.dll"]